services:
  mosquitto:
    image: eclipse-mosquitto
    ports: ["8883:8883"]
    volumes: ["./mosquitto:/mosquitto/config"]
    restart: unless-stopped

  nodered:
    build: .
    container_name: nodered-debian
    depends_on:
      - mosquitto
    ports:
      - "1880:1880"
    volumes:
      - nodered_debian_data:/data
      - ./datos:/data/datos
    restart: unless-stopped

  face-service:
    build: ./face-service
    container_name: face-service
    ports:
      - "5000:5000"
    volumes:
      - ./face-service/known_faces:/app/known_faces
    restart: unless-stopped

volumes:
  nodered_debian_data:
